const greysAnatomyCharacters = [
  'Derek',
  'Shepherd',
  'Meredith',
  'Grey',
  'Mark',
  'Sloan',
  'Yang',
  'Callie',
  'Izzie',
  'Arizona',
  'Bailey',
  "O'Malley",
  'Teddy',
  'Denny',
  'Duquette',
  'Maggie',
  'Adele',
  'Webber',
  'Karev',
  'Seattle',
  'Mercy West',
  'Alexandra',
  'Dr. Lexie Grey',
  'April',
  'Dr. April Kepner',
  'Dr. Arizona Robbins',
  'Calliope',
  'Dr. Callie Torres',
  'Cristina',
  'Dr.Cristina Yang',
  'Dr. Cristina Yang',
  'Erica',
  'Dr. Erica Hahn',
  'Ellis',
  'Meredith’s mother',
  'Torres',
  'Isobel',
  'Dr. Izzie Stevens',
  'Lucy',
  'Dr. Lucy Fields',
  'Shane',
  'Dr. Shane Ross',
  'Thatcher',
  'Meredith’s father',
  'Tucker',
  'Tyler',
  'Tyler Christian',
  'Margaret',
  'Dr. Margaret Campbell',
  'Dr. Meredith Grey',
  'Miranda',
  'Dr. Miranda Bailey',
  'Olivia',
  'Olivia Harper',
  'Sadie',
  'Dr. Sadie Harris',
  'Sydney',
  'Dr. Sydney Heron',
  'Theodora',
  'Dr. Teddy Altman',
  'Virginia',
  'Dr. Virginia Dixon',
  'Zola',
  'Alex',
  'Dr. Alex Karev',
  'Benjamin',
  'Dr. Ben Warren',
  'Colin',
  'Dr. Colin Marlowe',
  'Dr. Derek Shepherd',
  'Finn',
  'Dr. Finn Dandridge',
  'George',
  'Dr. George O’Malley',
  'Jackson',
  'Dr. Jackson Avery',
  'Dr. Mark Sloan',
  'Norman',
  'Dr. Norman Shales',
  'Preston',
  'Dr. Preston Burke',
  'Richard',
  'Dr. Richard Webber',
  'Robert',
  'Dr. Robert Stark',
  'Owen',
  'Dr. Owen Hunt',
];
const greysAnatomyWords = [
  ...greysAnatomyCharacters,
  'Chief',
  'Surgery',
  'surgicial',
  'surgeon',
  'orthopedics',
  'hospital',
  'cried',
  'push one of epi',
  "he's in V-Fib",
  "she's in V-Fib",
  'intubate him',
  'intubate her',
  'whipple',
  'get him up to CT',
  'get her up to CT',
  '10-blade',
  'start a central line',
  'my person',
  'cardio',
  'benign',
  'surgical resident',
  'a trauma surgical fellow',
  'chief of pediatric surgery',
  'orthopedic surgeon',
  'cardiac surgical fellow',
  'a surgical resident',
  'a cardiac surgeon',
  'an OB-GYN',
  'a general surgeon',
  'a nurse',
  'an intern',
  'a surgery resident',
  'an anesthesiologist',
  'a neurosurgeon',
  'a veterinarian',
  'a plastic surgeon',
  'chief of surgery',
  'a pediatric surgeon',
  'chief of plastic surgery',
  'my person',
];
const fillerWords = [
  'actual',
  'actually',
  'amazing',
  'anyway',
  'apparently',
  'approximately',
  'badly',
  'basically',
  'begin',
  'certainly',
  'clearly',
  'completely',
  'definitely',
  'easily',
  'effectively',
  'entirely',
  'especially',
  'essentially',
  'exactly',
  'extremely',
  'fairly',
  'frankly',
  'frequently',
  'fully',
  'generally',
  'hardly',
  'heavily',
  'highly',
  'hopefully',
  'just',
  'largely',
  'like',
  'literally',
  'maybe',
  'might',
  'most',
  'mostly',
  'much',
  'necessarily',
  'nicely',
  'obviously',
  'ok',
  'okay',
  'particularly',
  'perhaps',
  'possibly',
  'practically',
  'primarily',
  'probably',
  'precisely',
  'quite',
  'rather',
  'real',
  'really',
  'relatively',
  'right',
  'seriously',
  'significantly',
  'simply',
  'slightly',
  'so',
  'specifically',
  'start',
  'strongly',
  'stuff',
  'surely',
  'things',
  'too',
  'totally',
  'truly',
  'try',
  'typically',
  'ultimately',
  'usually',
  'very',
  'virtually',
  'whatever',
  'well',
  'whenever',
  'wherever',
  'whoever',
  'widely',
];

export default [...greysAnatomyWords, ...fillerWords];
