const greysAntomyWords = [
  "Derek",
  "Shepherd",
  "Meredith",
  "Grey",
  "Mark",
  "Sloan",
  "Yang",
  "Callie",
  "Izzie",
  "Arizona",
  "Bailey",
  "O'Malley",
  "Teddy",
  "Denny",
  "Duquette",
  "Maggie",
  "Adele",
  "Webber",
  "Karev",
  "Chief",
  "Surgery",
  "surgicial",
  "surgeon",
  "orthopedics",
  "hospital",
  "Seattle",
  "Mercy West",
  "cried",
  "push one of epi",
  "he's in V-Fib",
  "she's in V-Fib",
  "intubate him",
  "intubate her",
  "whipple",
  "get him up to CT",
  "get her up to CT",
  "10-blade",
  "start a central line",
  "my person",
  "cardio",
  "benign",
  "Alexandra",
  "Dr. Lexie Grey",
  "surgical resident",
  "April",
  "Dr. April Kepner",
  "a trauma surgical fellow",
  "Dr. Arizona Robbins",
  "chief of pediatric surgery",
  "Calliope",
  "Dr. Callie Torres",
  "orthopedic surgeon",
  "Cristina",
  "Dr.Cristina Yang",
  "cardiac surgical fellow",
  "Ellis",
  "Meredith’s mother",
  "Torres",
  "a surgical resident",
  "Dr. Cristina Yang",
  "Erica",
  "Dr. Erica Hahn",
  "a cardiac surgeon",
  "Isobel",
  "Dr. Izzie Stevens",
  "Lucy",
  "Dr. Lucy Fields",
  "an OB-GYN",
  "Margaret",
  "Dr. Margaret Campbell",
  "a general surgeon",
  "Dr. Meredith Grey",
  "Miranda",
  "Dr. Miranda Bailey",
  "Olivia",
  "Olivia Harper",
  "a nurse",
  "Sadie",
  "Dr. Sadie Harris",
  "an intern",
  "Sydney",
  "Dr. Sydney Heron",
  "a surgery resident",
  "Theodora",
  "Dr. Teddy Altman",
  "Virginia",
  "Dr. Virginia Dixon",
  "Zola",
  "Alex",
  "Dr. Alex Karev",
  "Benjamin",
  "Dr. Ben Warren",
  "an anesthesiologist",
  "Colin",
  "Dr. Colin Marlowe",
  "Dr. Derek Shepherd",
  "a neurosurgeon",
  "Finn",
  "Dr. Finn Dandridge",
  "a veterinarian",
  "George",
  "Dr. George O’Malley",
  "Jackson",
  "Dr. Jackson Avery",
  "a plastic surgeon",
  "Dr. Mark Sloan",
  "chief of plastic surgery",
  "Owen",
  "Dr. Owen Hunt",
  "chief of surgery",
  "Norman",
  "Dr. Norman Shales",
  "Preston",
  "Dr. Preston Burke",
  "Richard",
  "Dr. Richard Webber",
  "Robert",
  "Dr. Robert Stark",
  "a pediatric surgeon",
  "Shane",
  "Dr. Shane Ross",
  "Thatcher",
  "Meredith’s father",
  "Tucker",
  "Tyler",
  "Tyler Christian",
  "my person"
];
const fillerWords = [
  "actual",
  "actually",
  "amazing",
  "anyway",
  "apparently",
  "approximately",
  "badly",
  "basically",
  "begin",
  "certainly",
  "clearly",
  "completely",
  "definitely",
  "easily",
  "effectively",
  "entirely",
  "especially",
  "essentially",
  "exactly",
  "extremely",
  "fairly",
  "frankly",
  "frequently",
  "fully",
  "generally",
  "hardly",
  "heavily",
  "highly",
  "hopefully",
  "just",
  "largely",
  "like",
  "literally",
  "maybe",
  "might",
  "most",
  "mostly",
  "much",
  "necessarily",
  "nicely",
  "obviously",
  "ok",
  "okay",
  "particularly",
  "perhaps",
  "possibly",
  "practically",
  "primarily",
  "probably",
  "precisely",
  "quite",
  "rather",
  "real",
  "really",
  "relatively",
  "right",
  "seriously",
  "significantly",
  "simply",
  "slightly",
  "so",
  "specifically",
  "start",
  "strongly",
  "stuff",
  "surely",
  "things",
  "too",
  "totally",
  "truly",
  "try",
  "typically",
  "ultimately",
  "usually",
  "very",
  "virtually",
  "whatever",
  "well",
  "whenever",
  "wherever",
  "whoever",
  "widely"
];

export const WORDS = [...greysAntomyWords, ...fillerWords];
